<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.24" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SynthPay.Contracts\SynthPay.Contracts.csproj" />
    <ProjectReference Include="..\SynthPay.Transactions.Application\SynthPay.Transactions.Application.csproj" />
    <ProjectReference Include="..\SynthPay.Transactions.Domain\SynthPay.Transactions.Domain.csproj" />
  </ItemGroup>

</Project>
